# Generated by Django 3.0.3 on 2020-04-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='youremail',
            field=models.EmailField(default='kanak@gmail.com', max_length=254),
        ),
    ]
